In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


Bad key "text.kerning_factor" on line 4 in
C:\Users\Shamik Shetty\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution


# loading data

In [2]:
df_hotel = pd.read_csv("Hotel Reservations.csv")

df_hotel.head()

Booking_ID  no_of_adults  no_of_children  no_of_weekend_nights  \
0   INN00001             2               0                     1   
1   INN00002             2               0                     2   
2   INN00003             1               0                     2   
3   INN00004             2               0                     0   
4   INN00005             2               0                     1   

   no_of_week_nights type_of_meal_plan  required_car_parking_space  \
0                  2       Meal Plan 1                           0   
1                  3      Not Selected                           0   
2                  1       Meal Plan 1                           0   
3                  2       Meal Plan 1                           0   
4                  1      Not Selected                           0   

  room_type_reserved  lead_time  arrival_year  arrival_month  arrival_date  \
0        Room_Type 1        224          2017             10             2   
1        Room_Type 1          5          2018             11             6   
2        Room_Type 1          1          2018              2            28   
3        Room_Type 1        211          2018              5            20   
4        Room_Type 1         48          2018              4            11   

  market_segment_type  repeated_guest  no_of_previous_cancellations  \
0             Offline               0                             0   
1              Online               0                             0   
2              Online               0                             0   
3              Online               0                             0   
4              Online               0                             0   

   no_of_previous_bookings_not_canceled  avg_price_per_room  \
0                                     0               65.00   
1                                     0              106.68   
2                                     0               60.00   
3                                     0              100.00   
4                                     0               94.50   

   no_of_special_requests booking_status  
0                       0   Not_Canceled  
1                       1   Not_Canceled  
2                       0       Canceled  
3                       0       Canceled  
4                       0       Canceled

In [3]:
df_hotel.isnull().sum()

Booking_ID                              0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

In [4]:
df_hotel.dtypes

Booking_ID                               object
no_of_adults                              int64
no_of_children                            int64
no_of_weekend_nights                      int64
no_of_week_nights                         int64
type_of_meal_plan                        object
required_car_parking_space                int64
room_type_reserved                       object
lead_time                                 int64
arrival_year                              int64
arrival_month                             int64
arrival_date                              int64
market_segment_type                      object
repeated_guest                            int64
no_of_previous_cancellations              int64
no_of_previous_bookings_not_canceled      int64
avg_price_per_room                      float64
no_of_special_requests                    int64
booking_status                           object
dtype: object

In [5]:
df_hotel.describe()

no_of_adults  no_of_children  no_of_weekend_nights  no_of_week_nights  \
count  36275.000000    36275.000000          36275.000000       36275.000000   
mean       1.844962        0.105279              0.810724           2.204300   
std        0.518715        0.402648              0.870644           1.410905   
min        0.000000        0.000000              0.000000           0.000000   
25%        2.000000        0.000000              0.000000           1.000000   
50%        2.000000        0.000000              1.000000           2.000000   
75%        2.000000        0.000000              2.000000           3.000000   
max        4.000000       10.000000              7.000000          17.000000   

       required_car_parking_space     lead_time  arrival_year  arrival_month  \
count                36275.000000  36275.000000  36275.000000   36275.000000   
mean                     0.030986     85.232557   2017.820427       7.423653   
std                      0.173281     85.930817      0.383836       3.069894   
min                      0.000000      0.000000   2017.000000       1.000000   
25%                      0.000000     17.000000   2018.000000       5.000000   
50%                      0.000000     57.000000   2018.000000       8.000000   
75%                      0.000000    126.000000   2018.000000      10.000000   
max                      1.000000    443.000000   2018.000000      12.000000   

       arrival_date  repeated_guest  no_of_previous_cancellations  \
count  36275.000000    36275.000000                  36275.000000   
mean      15.596995        0.025637                      0.023349   
std        8.740447        0.158053                      0.368331   
min        1.000000        0.000000                      0.000000   
25%        8.000000        0.000000                      0.000000   
50%       16.000000        0.000000                      0.000000   
75%       23.000000        0.000000                      0.000000   
max       31.000000        1.000000                     13.000000   

       no_of_previous_bookings_not_canceled  avg_price_per_room  \
count                          36275.000000        36275.000000   
mean                               0.153411          103.423539   
std                                1.754171           35.089424   
min                                0.000000            0.000000   
25%                                0.000000           80.300000   
50%                                0.000000           99.450000   
75%                                0.000000          120.000000   
max                               58.000000          540.000000   

       no_of_special_requests  
count            36275.000000  
mean                 0.619655  
std                  0.786236  
min                  0.000000  
25%                  0.000000  
50%                  0.000000  
75%                  1.000000  
max                  5.000000

In [6]:
for i in df_hotel.columns:
    print({i:df_hotel[i].unique()})

{'Booking_ID': array(['INN00001', 'INN00002', 'INN00003', ..., 'INN36273', 'INN36274',
       'INN36275'], dtype=object)}
{'no_of_adults': array([2, 1, 3, 0, 4], dtype=int64)}
{'no_of_children': array([ 0,  2,  1,  3, 10,  9], dtype=int64)}
{'no_of_weekend_nights': array([1, 2, 0, 4, 3, 6, 5, 7], dtype=int64)}
{'no_of_week_nights': array([ 2,  3,  1,  4,  5,  0, 10,  6, 11,  7, 15,  9, 13,  8, 14, 12, 17,
       16], dtype=int64)}
{'type_of_meal_plan': array(['Meal Plan 1', 'Not Selected', 'Meal Plan 2', 'Meal Plan 3'],
      dtype=object)}
{'required_car_parking_space': array([0, 1], dtype=int64)}
{'room_type_reserved': array(['Room_Type 1', 'Room_Type 4', 'Room_Type 2', 'Room_Type 6',
       'Room_Type 5', 'Room_Type 7', 'Room_Type 3'], dtype=object)}
{'lead_time': array([224,   5,   1, 211,  48, 346,  34,  83, 121,  44,   0,  35,  30,
        95,  47, 256,  99,  12, 122,   2,  37, 130,  60,  56,   3, 107,
        72,  23, 289, 247, 186,  64,  96,  41,  55, 146,  32,  57,   7,
      

In [7]:
df_hotel.drop(["Booking_ID"], axis = 1, inplace = True)

In [10]:
sns.countplot(df_hotel.booking_status)

ValueError: could not convert string to float: 'Not_Canceled'

In [11]:
colname=[]
for x in df_hotel.columns:
    if df_hotel[x].dtype=="object":
        colname.append(x)
colname

['type_of_meal_plan',
 'room_type_reserved',
 'market_segment_type',
 'booking_status']

In [12]:
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()

for x in colname:
    df_hotel[x]=le.fit_transform(df_hotel[x])
    
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature type_of_meal_plan
mapping {'Meal Plan 1': 0, 'Meal Plan 2': 1, 'Meal Plan 3': 2, 'Not Selected': 3}
Feature room_type_reserved
mapping {'Room_Type 1': 0, 'Room_Type 2': 1, 'Room_Type 3': 2, 'Room_Type 4': 3, 'Room_Type 5': 4, 'Room_Type 6': 5, 'Room_Type 7': 6}
Feature market_segment_type
mapping {'Aviation': 0, 'Complementary': 1, 'Corporate': 2, 'Offline': 3, 'Online': 4}
Feature booking_status
mapping {'Canceled': 0, 'Not_Canceled': 1}


In [13]:
X=df_hotel.values[:,0:-1]
Y=df_hotel.values[:,-1]

In [14]:
print(X.shape)
print(Y.shape)


(36275, 17)
(36275,)


In [15]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X=scaler.fit_transform(X)#fit will lear mean and sigma values 
#scaler.fit_transform(X)
#X=scaler.transform(X)
print(X)

[[ 0.29889263 -0.26147045  0.2174012  ... -0.08745646 -1.09503276
  -0.78813999]
 [ 0.29889263 -0.26147045  1.36599262 ... -0.08745646  0.09280591
   0.48376045]
 [-1.62897546 -0.26147045  1.36599262 ... -0.08745646 -1.2375278
  -0.78813999]
 ...
 [ 0.29889263 -0.26147045  1.36599262 ... -0.08745646 -0.14345087
   1.75566089]
 [ 0.29889263 -0.26147045 -0.93119021 ... -0.08745646 -0.25431201
  -0.78813999]
 [ 0.29889263 -0.26147045  0.2174012  ... -0.08745646  1.65996637
  -0.78813999]]


# Building model logistic regression

In [16]:
#SPLITTING THE DATA
from sklearn.model_selection import train_test_split

#split the data into test and train 
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2,random_state=10)

In [17]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(29020, 17)
(29020,)
(7255, 17)
(7255,)


In [18]:
# BUILDING MODEL
from sklearn.linear_model import LogisticRegression
#create a model object 
classifier=LogisticRegression()
#train the model object
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(Y_pred)

[1. 1. 1. ... 1. 1. 0.]


In [19]:
#print(list(zip(Y_test,Y_pred)))

print(list(zip(df_hotel.columns[:-1],classifier.coef_.ravel()))) # coef_.ravel is used to flatten the array to avoid the problem of 1D and 2D Clash 


print(classifier.intercept_)
#classifier.coef_

[('no_of_adults', -0.016737866118598763), ('no_of_children', -0.014896366521899443), ('no_of_weekend_nights', -0.12101964222334197), ('no_of_week_nights', -0.07182852657697038), ('type_of_meal_plan', -0.0969211635214338), ('required_car_parking_space', 0.2540097088016597), ('room_type_reserved', 0.12484544411555465), ('lead_time', -1.1950626422889916), ('arrival_year', -0.21650000834939345), ('arrival_month', 0.1314058181458593), ('arrival_date', -0.027587978576134757), ('market_segment_type', -0.7740174644900476), ('repeated_guest', 0.23203595529244797), ('no_of_previous_cancellations', -0.045433676453922635), ('no_of_previous_bookings_not_canceled', 0.058839636032571065), ('avg_price_per_room', -0.6513377583029282), ('no_of_special_requests', 1.0839045402561636)]
[1.20916497]


In [20]:
#Evalution matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[1485  927]
 [ 483 4360]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.75      0.62      0.68      2412
         1.0       0.82      0.90      0.86      4843

    accuracy                           0.81      7255
   macro avg       0.79      0.76      0.77      7255
weighted avg       0.80      0.81      0.80      7255

Accuracy of the model:  0.8056512749827704


# Adjusting threshold

In [21]:
# store the predicted probabilities
#y_pred_prob=classifier.predict_proba(X_test)
#print(y_pred_prob)

In [25]:
#y_pred_class=[]
#for value in y_pred_prob[:,1]:
    #if value>0.50:
        #y_pred_class.append(1)
    #else:
    #y_pred_class.append(0)
#print(y_pred_class)

In [27]:
""""
#Evalution matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,y_pred_class)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,y_pred_class))

acc=accuracy_score(Y_test, y_pred_class)
print("Accuracy of the model: ",acc)
""""

SyntaxError: EOL while scanning string literal (<ipython-input-27-ad9735c98eda>, line 14)

# KNN

In [28]:
X=df_hotel.values[:,0:-1]
Y=df_hotel.values[:,-1]

In [29]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)#scaler object will learn on mu and sigma of all the variables
#scaler.fit_transform(X_train)
X=scaler.transform(X)#the knowledge from scaler object will be used to calculate the z score 

In [30]:
#SPLITTING THE DATA
from sklearn.model_selection import train_test_split

#split the data into test and train 
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2,random_state=10)

In [31]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(29020, 17)
(29020,)
(7255, 17)
(7255,)


In [32]:
# predicting using the Kneighbors Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))), metric='euclidean')

#euclidean, manhatten, minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train, Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test, Y_pred)))

[(0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 0.0), (0.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 1.0), (1.0, 1.0), (0.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 1.0), (1.0, 1.0), (0.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.

In [33]:
#Evalution matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[1500  912]
 [ 401 4442]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.79      0.62      0.70      2412
         1.0       0.83      0.92      0.87      4843

    accuracy                           0.82      7255
   macro avg       0.81      0.77      0.78      7255
weighted avg       0.82      0.82      0.81      7255

Accuracy of the model:  0.8190213645761544


# Hperparameter

In [34]:
np.sqrt(len(X_train))

170.35257556021864

In [35]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,50):
    model_KNN = KNeighborsClassifier(n_neighbors=K,metric="manhattan")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is  0.847553411440386 for K-Value: 1
Accuracy is  0.8177808407994487 for K-Value: 2
Accuracy is  0.8505858028945554 for K-Value: 3
Accuracy is  0.8413507925568573 for K-Value: 4
Accuracy is  0.8514128187456926 for K-Value: 5
Accuracy is  0.8457615437629221 for K-Value: 6
Accuracy is  0.850999310820124 for K-Value: 7
Accuracy is  0.8460372157133011 for K-Value: 8
Accuracy is  0.850447966919366 for K-Value: 9
Accuracy is  0.8468642315644384 for K-Value: 10
Accuracy is  0.8468642315644384 for K-Value: 11
Accuracy is  0.8436940041350792 for K-Value: 12
Accuracy is  0.8474155754651964 for K-Value: 13
Accuracy is  0.8456237077877325 for K-Value: 14
Accuracy is  0.8453480358373535 for K-Value: 15
Accuracy is  0.8447966919365955 for K-Value: 16
Accuracy is  0.8460372157133011 for K-Value: 17
Accuracy is  0.8467263955892488 for K-Value: 18
Accuracy is  0.8472777394900068 for K-Value: 19
Accuracy is  0.8454858718125431 for K-Value: 20
Accuracy is  0.8434183321847002 for K-Value: 21
Accu

In [36]:
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,":",my_dict[k])

5 : 0.8514128187456926


In [37]:
# predicting using the Kneighbors Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=3, metric='manhattan')

#euclidean, manhatten, minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train, Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test, Y_pred)))

[(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (1.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 0.0), (0.0, 1.0), (1.0, 1.0), (0.0, 1.0), (1.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (1.0, 1.0), (1.0, 1.0), (0.0, 0.0), (0.0, 0.0), (1.0, 1.0), (0.

In [38]:
#Evalution matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[1836  576]
 [ 508 4335]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.78      0.76      0.77      2412
         1.0       0.88      0.90      0.89      4843

    accuracy                           0.85      7255
   macro avg       0.83      0.83      0.83      7255
weighted avg       0.85      0.85      0.85      7255

Accuracy of the model:  0.8505858028945554


# Decision Tree

In [39]:
#SPLITTING THE DATA
from sklearn.model_selection import train_test_split

#split the data into test and train 
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.2,random_state=10)

In [40]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(29020, 17)
(29020,)
(7255, 17)
(7255,)


In [41]:
#predicting using the decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion="gini",random_state=10,splitter="best")# PRUNING => min_samples_leaf=2,min_samples_split=5, max_depth=10)

#fit the model on the data and predict the values
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

In [42]:
#Evalution matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[1939  473]
 [ 505 4338]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.79      0.80      0.80      2412
         1.0       0.90      0.90      0.90      4843

    accuracy                           0.87      7255
   macro avg       0.85      0.85      0.85      7255
weighted avg       0.87      0.87      0.87      7255

Accuracy of the model:  0.865196416264645


In [43]:
model_DecisionTree.score(X_train,Y_train)

0.9942453480358373

In [44]:
print((list(zip(df_hotel.columns[0:-1],model_DecisionTree.feature_importances_))))

[('no_of_adults', 0.026166530427897256), ('no_of_children', 0.00470485918395743), ('no_of_weekend_nights', 0.03603696244539272), ('no_of_week_nights', 0.04566347828649477), ('type_of_meal_plan', 0.012468313436842458), ('required_car_parking_space', 0.007559179262117128), ('room_type_reserved', 0.012166857658753052), ('lead_time', 0.35537381145952585), ('arrival_year', 0.01328313345988333), ('arrival_month', 0.07056388792864049), ('arrival_date', 0.07897528219714961), ('market_segment_type', 0.09582784064314719), ('repeated_guest', 0.0001845102931765503), ('no_of_previous_cancellations', 0.00040457303991384873), ('no_of_previous_bookings_not_canceled', 0.0003668101107512919), ('avg_price_per_room', 0.17163762095943083), ('no_of_special_requests', 0.06861634920692623)]


In [45]:
sample=pd.DataFrame()
 
sample["Column"]=df_hotel.columns[0:-1]
sample["Imp value"]=model_DecisionTree.feature_importances_
 
sample.sort_values("Imp value",ascending=False)

Column  Imp value
7                              lead_time   0.355374
15                    avg_price_per_room   0.171638
11                   market_segment_type   0.095828
10                          arrival_date   0.078975
9                          arrival_month   0.070564
16                no_of_special_requests   0.068616
3                      no_of_week_nights   0.045663
2                   no_of_weekend_nights   0.036037
0                           no_of_adults   0.026167
8                           arrival_year   0.013283
4                      type_of_meal_plan   0.012468
6                     room_type_reserved   0.012167
5             required_car_parking_space   0.007559
1                         no_of_children   0.004705
13          no_of_previous_cancellations   0.000405
14  no_of_previous_bookings_not_canceled   0.000367
12                        repeated_guest   0.000185

In [46]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DecisionTree, feature_names=df_hotel.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

In [47]:
#PRUNING
#predicting using the decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
my_dict={}
for n in range(2,10):
    for i in range(2,10):
        for z in range(2,10): 
            model_DecisionTree=DecisionTreeClassifier(criterion="gini",random_state=10,splitter="best",min_samples_leaf=n,min_samples_split=i, max_depth=10)
            model_DecisionTree.fit(X_train,Y_train) 
            Y_pred = model_DecisionTree.predict(X_test)
            print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for n-Value:",n,"for i-value",i,"for z-Value:",z)
            my_dict[n,i,z]=accuracy_score(Y_test,Y_pred)


Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 2 for z-Value: 2
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 2 for z-Value: 3
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 2 for z-Value: 4
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 2 for z-Value: 5
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 2 for z-Value: 6
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 2 for z-Value: 7
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 2 for z-Value: 8
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 2 for z-Value: 9
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 3 for z-Value: 2
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 3 for z-Value: 3
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 3 for z-Value: 4
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 3 for z-Value: 5
Accuracy is  0.8748449345279118 for n-Value: 2 for i-value 3 for z-Value: 6
Accuracy is 

Accuracy is  0.8741557546519642 for n-Value: 3 for i-value 7 for z-Value: 8
Accuracy is  0.8741557546519642 for n-Value: 3 for i-value 7 for z-Value: 9
Accuracy is  0.8740179186767746 for n-Value: 3 for i-value 8 for z-Value: 2
Accuracy is  0.8740179186767746 for n-Value: 3 for i-value 8 for z-Value: 3
Accuracy is  0.8740179186767746 for n-Value: 3 for i-value 8 for z-Value: 4
Accuracy is  0.8740179186767746 for n-Value: 3 for i-value 8 for z-Value: 5
Accuracy is  0.8740179186767746 for n-Value: 3 for i-value 8 for z-Value: 6
Accuracy is  0.8740179186767746 for n-Value: 3 for i-value 8 for z-Value: 7
Accuracy is  0.8740179186767746 for n-Value: 3 for i-value 8 for z-Value: 8
Accuracy is  0.8740179186767746 for n-Value: 3 for i-value 8 for z-Value: 9
Accuracy is  0.8734665747760165 for n-Value: 3 for i-value 9 for z-Value: 2
Accuracy is  0.8734665747760165 for n-Value: 3 for i-value 9 for z-Value: 3
Accuracy is  0.8734665747760165 for n-Value: 3 for i-value 9 for z-Value: 4
Accuracy is 

Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 5 for z-Value: 5
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 5 for z-Value: 6
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 5 for z-Value: 7
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 5 for z-Value: 8
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 5 for z-Value: 9
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 6 for z-Value: 2
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 6 for z-Value: 3
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 6 for z-Value: 4
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 6 for z-Value: 5
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 6 for z-Value: 6
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 6 for z-Value: 7
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 6 for z-Value: 8
Accuracy is  0.8712611991729842 for n-Value: 5 for i-value 6 for z-Value: 9
Accuracy is 

Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 3 for z-Value: 2
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 3 for z-Value: 3
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 3 for z-Value: 4
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 3 for z-Value: 5
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 3 for z-Value: 6
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 3 for z-Value: 7
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 3 for z-Value: 8
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 3 for z-Value: 9
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 4 for z-Value: 2
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 4 for z-Value: 3
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 4 for z-Value: 4
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 4 for z-Value: 5
Accuracy is  0.8715368711233632 for n-Value: 7 for i-value 4 for z-Value: 6
Accuracy is 

Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 8 for z-Value: 7
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 8 for z-Value: 8
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 8 for z-Value: 9
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 9 for z-Value: 2
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 9 for z-Value: 3
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 9 for z-Value: 4
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 9 for z-Value: 5
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 9 for z-Value: 6
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 9 for z-Value: 7
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 9 for z-Value: 8
Accuracy is  0.8702963473466575 for n-Value: 8 for i-value 9 for z-Value: 9
Accuracy is  0.8720882150241213 for n-Value: 9 for i-value 2 for z-Value: 2
Accuracy is  0.8720882150241213 for n-Value: 9 for i-value 2 for z-Value: 3
Accuracy is 

In [48]:
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,":",my_dict[k])

(2, 8, 2) : 0.8751206064782908
(2, 8, 3) : 0.8751206064782908
(2, 8, 4) : 0.8751206064782908
(2, 8, 5) : 0.8751206064782908
(2, 8, 6) : 0.8751206064782908
(2, 8, 7) : 0.8751206064782908
(2, 8, 8) : 0.8751206064782908
(2, 8, 9) : 0.8751206064782908


In [49]:
#Evalution matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[1899  513]
 [ 415 4428]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.82      0.79      0.80      2412
         1.0       0.90      0.91      0.91      4843

    accuracy                           0.87      7255
   macro avg       0.86      0.85      0.85      7255
weighted avg       0.87      0.87      0.87      7255

Accuracy of the model:  0.8720882150241213


# SVM Classifier

In [50]:
from sklearn.svm import SVC
svc_model=SVC(kernel='rbf',C=20,gamma=0.01)#previous c=1,gamma=0.01
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)
print(list(Y_pred))

[1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

In [51]:
svc_model.score(X_train,Y_train)

0.8373535492763611

In [52]:
#Evalution matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[1583  829]
 [ 411 4432]]
Classification report: 
              precision    recall  f1-score   support

         0.0       0.79      0.66      0.72      2412
         1.0       0.84      0.92      0.88      4843

    accuracy                           0.83      7255
   macro avg       0.82      0.79      0.80      7255
weighted avg       0.83      0.83      0.82      7255

Accuracy of the model:  0.8290833907649897


In [53]:
from sklearn import svm
 
svc_model = svm.SVC(kernel="rbf")
 
parameter_space = {
    #'kernel': ["linear","rbf","poly","sigmoid"],
    'gamma': [0.1,0.01,0.001],
    #"C": np.arange(0,101,5)
    'C': [1,5,8,10,20,30, 40,50,130]
    
}
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svc_model, parameter_space, n_jobs=-1, cv=5)

In [54]:
#clf.fit(X_train,Y_train)

In [55]:
#print('Best parameters found:\n',clf.best_params_)

In [56]:
#clf.best_score_  #accuracy of the best params using 5-fold cv

In [57]:
#clf.score(X_train,Y_train) #accuracy of the best paramson the train data

In [58]:
#Y_pred=clf.predict(X_test)
#print(list(Y_pred))

In [59]:
#Y_pred.sum()